"""empty message

Revision ID: 9753b0a6d562
Revises: 8b348cb5fa6c
Create Date: 2022-09-14 22:57:26.885217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9753b0a6d562'
down_revision = '8b348cb5fa6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    # ### end Alembic commands ###
